#!/usr/bin/php
<?php

use Dotenv\Dotenv;
use PHPServer\BuiltIn\Server;

require 'vendor/autoload.php';

Dotenv::createImmutable(__DIR__)->load();

Server::create($_SERVER['SERVER_HOST'], $_SERVER['SERVER_PORT'])
    ->setRouterScript(__DIR__ . '/public/index.php')
    ->setDocumentRoot(__DIR__ . '/public')
    ->setWorkers(3)
    ->start()
    ->logOutputToConsole();