#!/usr/bin/php
<?php

use App\Core\Bootstrap;
use Dotenv\Dotenv;
use PHPServer\BuiltIn\Server;

require 'vendor/autoload.php';

const ROOT_DIR = __DIR__;

Bootstrap::performInitialChecks();

Dotenv::createImmutable(__DIR__)->load();

Server::create($_SERVER['SERVER_HOST'], $_SERVER['SERVER_PORT'])
    ->setRouterScript(__DIR__ . '/public/index.php')
    ->setDocumentRoot(__DIR__ . '/public')
    ->setWorkers(3)
    ->start()
    ->logOutputToConsole();